services:
  ubuntu:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./test:/test
    command: tail -f /dev/null

  alpine:
    build:
      context: .
      dockerfile: ./build/Dockerfile.alpine
    volumes:
      - ./test:/test
    command: tail -f /dev/null