# build/Dockerfileを使って、イメージ densukest/xampp-devenv:latest をビルドする
# ビルド後イメージを densukest/xampp-devenv:latest としてpushする

name: Docker Image CI

on:
    push:
        branches-ignore:
        - release/*
    pull_request:
        branches-ignore:
        - release/*
    workflow_dispatch: # 手動実行

jobs:
    build:
        #runs-on: self-hosted
        runs-on: ubuntu-latest

        steps:
        - name: ブランチ名を取得して環境変数にセット
          run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        - name: もしBRANCH_NAMEがmainならlatestに変更
          run: |
            if [ $BRANCH_NAME = "main" ]; then
              echo "BRANCH_NAME=latest" >> $GITHUB_ENV
            fi
        - name: 変数BRANCH_NAMEの値を出力
          run: echo $BRANCH_NAME
        - name: チェックアウト
          uses: actions/checkout@v4
        - name: "buildx: QEMUのセットアップ"
          uses: docker/setup-qemu-action@v3
        - name: "docker buildの準備"
          uses: docker/setup-buildx-action@v3
        - name: "dockerへのログイン"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: "イメージのビルド、push時のタグはBRANCH_NAME変数の値を使う"
          uses: docker/build-push-action@v5
          with:
            context: build
            platforms: linux/amd64,linux/arm64
            push: true
            tags: densukest/xampp-devenv:${{ env.BRANCH_NAME }}

