# build/Dockerfileを使って、イメージ densukest/xampp-devenv:latest をビルドする
# ビルド後イメージを densukest/xampp-devenv:latest としてpushする

name: イメージビルドのテスト

on:
    push:
        branches-ignore:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch: # 手動実行

jobs:

    # actで実行しているかのチェック(一部のアクションを動かさないようにするため)
    check-act:
      runs-on: ubuntu-latest
      outputs:
        IS_ACT: ${{ steps.check-act.outputs.IS_ACT }}
      steps:
        - name: actのチェック
          id: check-act
          run: |
            if [ -n "$ACT" ]; then
              echo "IS_ACT=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "IS_ACT=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            # もしこの起動がプルリクであれば、同様にIS_ACTを設定して代用する
            if [ -n "$GITHUB_EVENT_NAME" ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              echo "IS_ACT=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "IS_ACT=false" >> $GITHUB_OUTPUT
              exit 0
            fi
    build:
        needs:
          - check-act
        strategy:
          fail-fast: true
          matrix:
            include:
              - platform: linux/amd64
                runner: ubuntu-24.04
                tag_suffix: amd64
              - platform: linux/arm64
                runner: ${{ needs.check-act.outputs.IS_ACT == 'true' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
                tag_suffix: arm64
        runs-on: ${{ matrix.runner }}
        steps:
        - name: チェックアウト
          uses: actions/checkout@v4
        - name: "buildx: QEMUのセットアップ"
          uses: docker/setup-qemu-action@v3
        - name: "docker buildの準備"
          uses: docker/setup-buildx-action@v3
        - name: "dockerへのログイン"
          uses: docker/login-action@v3
          if: needs.check-act.outputs.IS_ACT != 'true'
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: "イメージのビルド"
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./build/Dockerfile
            platforms: ${{ matrix.platform }}
            push: ${{ needs.check-act.outputs.IS_ACT != 'true' }}
            load: ${{ needs.check-act.outputs.IS_ACT == 'true' }}
            tags: densukest/xampp-devenv:testing-${{ matrix.tag_suffix }}
        - name: "(act上)イメージの削除"
          if: needs.check-act.outputs.IS_ACT == 'true'
          run: |
            docker rmi densukest/xampp-devenv:testing-${{ matrix.tag_suffix }} || true
    